name: duf # you probably want to 'snapcraft register <name>'
version: '0.8.1'
summary: Disk Usage/Free Utility - a better 'df' alternative
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
base: core20
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  duf:
    # See 'snapcraft plugins'
    plugin: go
    source: https://github.com/muesli/duf.git
    source-tag: v0.8.1

apps:
  duf:
    command: bin/duf
